@DemoAPI_HostAddress = https://localhost:7187

GET {{DemoAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DemoAPI_HostAddress}}/devinfo/
Accept: application/json
X-Test-Header: Hello, World!

###

GET {{DemoAPI_HostAddress}}/helloWorld/
Accept: application/json

###

GET {{DemoAPI_HostAddress}}/someData/
Accept: application/json

###